version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: base64:YHwUsAiZq9VkDQbNEDY8PG21dSiLMT1MrFjHaxEns+M=
      APP_DEBUG: true
      APP_URL: ${APP_URL}

      APP_LOCALE: id
      APP_FALLBACK_LOCALE: id
      APP_FAKER_LOCALE: id_ID

      APP_MAINTENANCE_DRIVER: file
      # APP_MAINTENANCE_STORE: database

      PHP_CLI_SERVER_WORKERS: 4

      BCRYPT_ROUNDS: 12

      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null

      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local   
      QUEUE_CONNECTION: database

      CACHE_STORE: database
      # CACHE_PREFIX: 

      MEMCACHED_HOST: 127.0.0.1

      REDIS_CLIENT: phpredis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PASSWORD}

      MAIL_MAILER: log
      MAIL_SCHEME: null
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: 
      AWS_USE_PATH_STYLE_ENDPOINT: false

      VITE_APP_NAME: "${APP_NAME}"

    volumes:
      - laravel_code:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - laravel_code:/var/www/html:ro
    networks:
      - laravel
volumes:
  laravel_code:

networks:
  laravel:
